sonar.projectKey=pablitoo5_TPIntegradorSeguridadBGMP
sonar.organization=tpi-seguridad-bgmp

# Directorios a escanear
sonar.sources=.

# Directorios a ignorar
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**
